// Generated by CoffeeScript 1.6.3
(function() {
  var https, post;

  https = require('https');

  post = function(query, callback) {
    var key, options, request, value;
    options = {
      host: 'www.google-analytics.com',
      path: '/collect'
    };
    request = https.request(options, function(res) {
      console.log(res.statusCode);
      if (res.statusCode !== 200) {
        return callback(new Error('cannot send for collection'));
      }
      return res.on('close', callback);
    });
    request.on('error', function(error) {
      return callback(error);
    });
    request.write(((function() {
      var _results;
      _results = [];
      for (key in query) {
        value = query[key];
        if (value) {
          _results.push("" + key + "=" + (encodeURIComponent(value)));
        }
      }
      return _results;
    })()).join('&'));
    return request.end();
  };

  exports.middleware = function(config) {
    if (config == null) {
      config = {};
    }
    return function(req, res, next) {
      var _base, _base1;
      if (res.ga == null) {
        res.ga = res.analytics != null ? res.analytics : res.analytics = {};
      }
      if ((_base = res.ga).collect == null) {
        _base.collect = (_base1 = res.analytics).collect != null ? (_base1 = res.analytics).collect : _base1.collect = {};
      }
      res.ga.collect.event = res.analytics.collect.event = function(options, callback) {
        var query;
        if (options == null) {
          options = {};
        }
        if (callback == null) {
          callback = function() {};
        }
        query = {
          v: 1,
          tid: options.trackingId || config.trackingId || null,
          cid: options.clientId || null,
          t: 'event',
          ec: options.category || null,
          ea: options.action || null,
          el: options.label || null,
          ev: options.value || null
        };
        if (!query.tid) {
          return callback(new Error('no tracking id specified'));
        }
        if (!query.cid) {
          return callback(new Error('no client id specified'));
        }
        if (!query.ec) {
          return callback(new Error('no category specified'));
        }
        if (!query.ea) {
          return callback(new Error('no action specified'));
        }
        if (config.debug || options.debug) {
          if (config.debug || options.debug) {
            return console.log(query);
          }
        } else {
          return post(query, callback);
        }
      };
      return next();
    };
  };

}).call(this);
